//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package types

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAN) DeepCopyInto(out *SAN) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAN.
func (in *SAN) DeepCopy() *SAN {
	if in == nil {
		return nil
	}
	out := new(SAN)
	in.DeepCopyInto(out)
	return out
}
